# Phần 1: Khám phá tenser

## Task 1.1 Tạo tenser

In [ ]:
import torch
import numpy as np
# Tạo tensor từ list
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f"Tensor từ list:\r\n {x_data}\r\n")
# Tạo tensor từ NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"Tensor từ NumPy array:\r\n {x_np}\r\n")
# Tạo tensor với các giá trị ngẫu nhiên hoặc hằng số
x_ones = torch.ones_like(x_data) # tạo tensor gồm các số 1 có cùng shape với x_data
print(f"Ones Tensor:\r\n {x_ones}\r\n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # tạo tensor ngẫu nhiên
print(f"Random Tensor:\r\n {x_rand}\r\n")
# In ra shape, dtype, và device của tensor
print(f"Shape của tensor: {x_rand.shape}")
print(f"Datatype của tensor: {x_rand.dtype}")
print(f"Device lưu trữ tensor: {x_rand.device}")

Tensor từ list:
 tensor([[1, 2],
        [3, 4]])

Tensor từ NumPy array:
 tensor([[1, 2],
        [3, 4]])

Ones Tensor:
 tensor([[1, 1],
        [1, 1]])

Random Tensor:
 tensor([[0.2043, 0.0215],
        [0.8060, 0.0162]])

Shape của tensor: torch.Size([2, 2])
Datatype của tensor: torch.float32
Device lưu trữ tensor: cpu


## Task 1.2 Các phép toán trên Tensor

In [ ]:
# 1. Cộng x_data với chính nó
# Phép toán: [[1, 2], [3, 4]] + [[1, 2], [3, 4]]
sum_tensor = x_data + x_data
print(f"1. Cộng x_data với chính nó:\n {sum_tensor}\r\n")

# 2. Nhân x_data với 5
# Phép toán: [[1, 2], [3, 4]] * 5
mult_tensor = x_data * 5
print(f"2. Nhân x_data với 5:\r\n {mult_tensor}\r\n")

# 3. Nhân ma trận x_data với x_data.T (ma trận chuyển vị)
# x_data.T (chuyển vị) là: [[1, 3], [2, 4]]
# Phép toán: [[1, 2], [3, 4]] @ [[1, 3], [2, 4]]
matmul_tensor = x_data @ x_data.T
print(f"3. Nhân ma trận (x_data @ x_data.T):\r\n {matmul_tensor}\r\n")

1. Cộng x_data với chính nó:
 tensor([[2, 4],
        [6, 8]])

2. Nhân x_data với 5:
 tensor([[ 5, 10],
        [15, 20]])

3. Nhân ma trận (x_data @ x_data.T):
 tensor([[ 5, 11],
        [11, 25]])



## Task 1.3 Indexing và Slicing

In [ ]:
print(f"Tensor gốc x_data:\r\n {x_data}\r\n")

# 1. Lấy ra hàng đầu tiên (chỉ số 0)
first_row = x_data[0] # Hoặc x_data[0, :]
print(f"1. Hàng đầu tiên: {first_row}")

# 2. Lấy ra cột thứ hai (chỉ số 1)
second_col = x_data[:, 1]
print(f"2. Cột thứ hai: {second_col}")

# 3. Lấy ra giá trị ở hàng thứ hai (chỉ số 1), cột thứ hai (chỉ số 1)
value = x_data[1, 1] # Hoặc x_data[1][1]
print(f"3. Giá trị (hàng 2, cột 2): {value}\r\n")

Tensor gốc x_data:
 tensor([[1, 2],
        [3, 4]])

1. Hàng đầu tiên: tensor([1, 2])
2. Cột thứ hai: tensor([2, 4])
3. Giá trị (hàng 2, cột 2): 4



## Task 1.4: Thay đổi hình dạng Tensor

In [ ]:
# 1. Sử dụng torch.rand để tạo một tensor có shape (4, 4)
tensor_4x4 = torch.rand(4, 4)
print(f"Tensor 4x4 ban đầu (shape {tensor_4x4.shape}):\r\n {tensor_4x4}\r\n")

# 2. Sử dụng hàm view để biến nó thành (16, 1)
# Tổng số phần tử phải giữ nguyên (4*4 = 16*1 = 16)
tensor_16x1 = tensor_4x4.view(16, 1)

# Bạn cũng có thể dùng reshape, cách này an toàn hơn một chút
# tensor_16x1 = tensor_4x4.reshape(16, 1)

print(f"Tensor 16x1 sau khi reshape (shape {tensor_16x1.shape}):\r\n {tensor_16x1}")

Tensor 4x4 ban đầu (shape torch.Size([4, 4])):
 tensor([[0.0538, 0.4079, 0.3312, 0.7350],
        [0.2069, 0.9069, 0.6259, 0.6252],
        [0.5081, 0.6977, 0.3663, 0.7399],
        [0.7282, 0.5946, 0.2697, 0.6460]])

Tensor 16x1 sau khi reshape (shape torch.Size([16, 1])):
 tensor([[0.0538],
        [0.4079],
        [0.3312],
        [0.7350],
        [0.2069],
        [0.9069],
        [0.6259],
        [0.6252],
        [0.5081],
        [0.6977],
        [0.3663],
        [0.7399],
        [0.7282],
        [0.5946],
        [0.2697],
        [0.6460]])


# Phần 2: Tự động tính Đạo hàm với autograd

## Task 2.1: Thực hành với autograd

In [5]:
# Tạo một tensor và yêu cầu tính đạo hàm cho nó
x = torch.ones(1, requires_grad=True)
print(f"x: {x}")
# Thực hiện một phép toán
y = x + 2
print(f"y: {y}")
# y được tạo ra từ một phép toán có x, nên nó cũng có grad_fn
print(f"grad_fn của y: {y.grad_fn}")
# Thực hiện thêm các phép toán
z = y * y * 3
# Tính đạo hàm của z theo x
z.backward() # tương đương z.backward(torch.tensor(1.))
# Đạo hàm được lưu trong thuộc tính .grad
# Ta có z = 3 * (x+2)^2 => dz/dx = 6 * (x+2). Với x=1, dz/dx = 18
print(f"Đạo hàm của z theo x: {x.grad}")

x: tensor([1.], requires_grad=True)
y: tensor([3.], grad_fn=<AddBackward0>)
grad_fn của y: <AddBackward0 object at 0x7d58511560e0>
Đạo hàm của z theo x: tensor([18.])


1. Chuyện gì xảy ra?
Khi gọi z.backward() lần thứ hai, chương trình sẽ báo lỗi RuntimeError:

`RuntimeError: trying to differentiate through the graph a second time, but the saved intermediate results have already been freed.`

2. Tại sao?
Theo mặc định, PyTorch tự động xóa biểu đồ tính toán (computational graph) ngay sau khi gọi .backward() lần đầu tiên.

- Biểu đồ tính toán: Là một cấu trúc dữ liệu ghi lại tất cả các phép toán (như y = x + 2, z = y*y*3) để biết cách tính đạo hàm.

- Tối ưu hóa bộ nhớ: PyTorch làm điều này để giải phóng bộ nhớ. Trong một vòng lặp huấn luyện (training loop) thông thường, chúng ta chỉ cần tính đạo hàm một lần cho mỗi batch, cập nhật trọng số, rồi vứt bỏ biểu đồ cũ để chuẩn bị cho batch tiếp theo.

- Lỗi ở lần gọi thứ hai: Khi gọi z.backward() lần thứ hai, PyTorch không còn tìm thấy biểu đồ đó nữa nên không thể tính đạo hàm và báo lỗi.

# Phần 3: Xây dựng Mô hình đầu tiên với torch.nn

## Task 3.1: Lớp nn.Linear

In [ ]:
# Khởi tạo một lớp Linear biến đổi từ 5 chiều -> 2 chiều
linear_layer = torch.nn.Linear(in_features=5, out_features=2)
# Tạo một tensor đầu vào mẫu
input_tensor = torch.randn(3, 5) # 3 mẫu, mỗi mẫu 5 chiều
# Truyền đầu vào qua lớp linear
output = linear_layer(input_tensor)
print(f"Input shape: {input_tensor.shape}")
print(f"Output shape: {output.shape}")
print(f"Output:\r\n {output}")

Input shape: torch.Size([3, 5])
Output shape: torch.Size([3, 2])
Output:
 tensor([[-0.6791,  0.1990],
        [ 0.1841,  0.8771],
        [-0.7654,  0.7938]], grad_fn=<AddmmBackward0>)


## Task 3.2: Lớp nn.Embedding

In [ ]:
# Khởi tạo lớp Embedding cho một từ điển 10 từ, mỗi từ biểu diễn bằng vector 3 chiều
embedding_layer = torch.nn.Embedding(num_embeddings=10, embedding_dim=3)
# Tạo một tensor đầu vào chứa các chỉ số của từ (ví dụ: một câu)
# Các chỉ số phải nhỏ hơn 10
input_indices = torch.LongTensor([1, 5, 0, 8])
# Lấy ra các vector embedding tương ứng
embeddings = embedding_layer(input_indices)
print(f"Input shape: {input_indices.shape}")
print(f"Output shape: {embeddings.shape}")
print(f"Embeddings:\r\n {embeddings}")

Input shape: torch.Size([4])
Output shape: torch.Size([4, 3])
Embeddings:
 tensor([[-6.5675e-01, -1.5272e+00,  3.9863e-01],
        [ 5.0925e-04, -5.0854e-01, -2.7003e-01],
        [-2.5135e+00, -6.4787e-01,  1.3967e+00],
        [-3.0721e-02,  1.3076e-01, -1.0061e+00]], grad_fn=<EmbeddingBackward0>)


## Task 3.3: Kết hợp thành một nn.Module

In [8]:
from torch import nn
class MyFirstModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
        super(MyFirstModel, self).__init__()
        # Định nghĩa các lớp (layer) bạn sẽ dùng
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.linear = nn.Linear(embedding_dim, hidden_dim)
        self.activation = nn.ReLU() # Hàm kích hoạt
        self.output_layer = nn.Linear(hidden_dim, output_dim)
    def forward(self, indices):
        # Định nghĩa luồng dữ liệu đi qua các lớp
        # 1. Lấy embedding
        embeds = self.embedding(indices)
        # 2. Truyền qua lớp linear và hàm kích hoạt
        hidden = self.activation(self.linear(embeds))
        # 3. Truyền qua lớp output
        output = self.output_layer(hidden)
        return output
# Khởi tạo và kiểm tra mô hình
model = MyFirstModel(vocab_size=100, embedding_dim=16, hidden_dim=8, output_dim=2)
input_data = torch.LongTensor([[1, 2, 5, 9]]) # một câu gồm 4 từ
output_data = model(input_data)
print(f"Model output shape: {output_data.shape}")

Model output shape: torch.Size([1, 4, 2])
